Sleep(5000)
ControlFocus("Open","","Edit1")
ControlSetText("Open","","Edit1","E:\SeleniumProjects\NaukriApiMVN1\Automation\TestReport\JobSummaryReport.xlsx")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlClick("Open","","Button1")
Sleep(2000)